
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag:
        type: text
        required: true
        description: Tag

permissions: write-all

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu, macos]

    runs-on: ${{ matrix.os }}-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        CGO_ENABLED=0 go build -v ./...

    - name: Release
      if: github.event_name == 'workflow_dispatch'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        TAG=${{ github.event.inputs.tag }}
        TGZ=kafka-tools-${{ matrix.os }}.tgz
        tar czf $TGZ kafka-tools

        gh release create $TAG $TGZ || gh release upload $TAG $TGZ
