
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag:
        type: text
        required: true
        description: Tag


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      env:
        CGO_ENABLED: '0'
      run: go build -v ./...

    - name: Release
      if: github.event_name == 'workflow_dispatch'
      run: |
        gh release create "${{ github.event.inputs.tag }}" kafka-tools
