name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Tag

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: |
          CGO_ENABLED=0 go build -v ./...

      - name: Release
        if: github.event_name == 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ github.token }}
          OS_NAME: ${{ matrix.os == 'ubuntu' && 'linux' || matrix.os }} # ubuntu => linux
        run: |
          TAG=${{ github.event.inputs.tag }}
          TGZ_FILE=kafka-tools-$OS_NAME.tar.gz
          tar czf $TGZ_FILE kafka-tools

          # Create or update release
          gh release create $TAG $TGZ_FILE || gh release upload $TAG $TGZ_FILE
